/**
 * MAYAVERSE - Airtable Service
 *
 * Secure communication with Airtable to store and retrieve user records.
 * Field names exactly match the Airtable table columns.
 *
 * Airtable Columns:
 * - Name
 * - Email
 * - Phone Number
 * - College Name
 * - User Type      ('BIT' / 'NON_BIT')
 * - Payment Status ('Free' / 'Pending' / 'Verified')
 * - Timestamp      (auto-generated by Airtable)
 * - Notes          (used to store transactionId + passwordHash)
 * - Source (Website/Page)
 * - Email Notification Sent
 */

const API_KEY = import.meta.env.VITE_AIRTABLE_TOKEN;
const BASE_ID = import.meta.env.VITE_AIRTABLE_BASE_ID;
const TABLE_NAME = import.meta.env.VITE_AIRTABLE_TABLE_NAME || 'Registrations';

const BASE_URL = `https://api.airtable.com/v0/${BASE_ID}/${encodeURIComponent(TABLE_NAME)}`;

/**
 * Fetch a user from Airtable by email
 * @param {string} email
 * @returns {Promise<object|null>} The user record or null if not found
 */
export const getUserByEmail = async (email) => {
    const filter = `({Email} = '${email.trim()}')`;
    const url = `${BASE_URL}?filterByFormula=${encodeURIComponent(filter)}`;

    try {
        const response = await fetch(url, {
            headers: {
                Authorization: `Bearer ${API_KEY}`,
            },
        });

        if (!response.ok) {
            const errData = await response.json();
            throw new Error(errData.error?.message || 'Airtable connection failed');
        }

        const data = await response.json();
        if (data.records && data.records.length > 0) {
            const record = data.records[0];
            const f = record.fields;

            // Parse Notes field which stores: "hash:<hash>|txn:<transactionId>"
            let passwordHash = '';
            let transactionId = '';
            if (f['Notes']) {
                const hashMatch = f['Notes'].match(/hash:([^|]+)/);
                const txnMatch = f['Notes'].match(/txn:([^|]+)/);
                if (hashMatch) passwordHash = hashMatch[1];
                if (txnMatch) transactionId = txnMatch[1];
            }

            return {
                airtableId: record.id,
                name: f['Name'] || '',
                email: f['Email'] || '',
                phone: f['Phone Number'] || '',
                college: f['College Name'] || '',
                user_type: f['User Type'] || '',
                payment_status: f['Payment Status'] || '',
                passwordHash,
                transactionId,
                registeredEvents: [],
            };
        }
        return null;
    } catch (error) {
        console.error('Error fetching user from Airtable:', error);
        throw error;
    }
};

/**
 * Create a new user record in Airtable
 * Uses existing columns only. Stores passwordHash + transactionId in Notes.
 * @param {object} userData
 * @returns {Promise<object>} The newly created user record
 */
export const createUser = async (userData) => {
    try {
        // Pack hash and transactionId into Notes since no dedicated column exists
        const notes = `hash:${userData.passwordHash || ''}|txn:${userData.transactionId || ''}`;

        const fields = {
            'Name': userData.name || '',
            'Email': userData.email || '',
            'Phone Number': userData.phone || '',
            'College Name': userData.college || '',
            'User Type': userData.user_type || 'NON_BIT',
            'Payment Status': userData.payment_status || 'Pending',
            'Notes': notes,
            'Source (Website/Page)': 'Mayaverse Website',
        };

        const response = await fetch(BASE_URL, {
            method: 'POST',
            headers: {
                Authorization: `Bearer ${API_KEY}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ fields }),
        });

        if (!response.ok) {
            const errData = await response.json();
            throw new Error(errData.error?.message || 'Failed to create user in Airtable');
        }

        const data = await response.json();
        const f = data.fields;

        return {
            airtableId: data.id,
            name: f['Name'] || '',
            email: f['Email'] || '',
            phone: f['Phone Number'] || '',
            college: f['College Name'] || '',
            user_type: f['User Type'] || '',
            payment_status: f['Payment Status'] || '',
            passwordHash: userData.passwordHash,
            transactionId: userData.transactionId,
            registeredEvents: [],
        };
    } catch (error) {
        console.error('Error creating user in Airtable:', error);
        throw error;
    }
};

/**
 * Update an existing user record
 * @param {string} airtableId
 * @param {object} updates
 * @returns {Promise<object>} The updated user record
 */
export const updateUserRecord = async (airtableId, updates) => {
    try {
        const fields = {};
        if (updates.name !== undefined) fields['Name'] = updates.name;
        if (updates.phone !== undefined) fields['Phone Number'] = updates.phone;
        if (updates.college !== undefined) fields['College Name'] = updates.college;
        if (updates.payment_status !== undefined) fields['Payment Status'] = updates.payment_status;

        const response = await fetch(`${BASE_URL}/${airtableId}`, {
            method: 'PATCH',
            headers: {
                Authorization: `Bearer ${API_KEY}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ fields }),
        });

        if (!response.ok) {
            const errData = await response.json();
            throw new Error(errData.error?.message || 'Failed to update user in Airtable');
        }

        const data = await response.json();
        const f = data.fields;
        return {
            airtableId: data.id,
            name: f['Name'] || '',
            email: f['Email'] || '',
            payment_status: f['Payment Status'] || '',
        };
    } catch (error) {
        console.error('Error updating user in Airtable:', error);
        throw error;
    }
};

export default {
    getUserByEmail,
    createUser,
    updateUserRecord,
};
